# Generated by Django 5.0.3 on 2024-04-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporttool', '0003_column_entity_usermodel_delete_entities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(max_length=100)),
                ('clientId', models.CharField(max_length=100)),
                ('clientSecret', models.CharField(max_length=100)),
            ],
        ),
    ]
