# Generated by Django 5.0.3 on 2024-06-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporttool', '0006_sftpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sftpconfig',
            name='name',
            field=models.CharField(default='SFTP Name', max_length=100),
        ),
    ]
