# Generated by Django 5.0.3 on 2024-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporttool', '0007_sftpconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sftpconfig',
            name='directory',
            field=models.CharField(default='.', max_length=250),
        ),
    ]
