# Generated by Django 5.0.3 on 2024-10-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporttool', '0009_s3config_alter_sftpconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='related_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_entities', to='exporttool.entity'),
        ),
    ]
