# Generated by Django 5.1.2 on 2024-11-06 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxxconfig',
            old_name='clientId',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='fluxxconfig',
            old_name='clientSecret',
            new_name='client_secret',
        ),
        migrations.RenameField(
            model_name='s3config',
            old_name='accessKey',
            new_name='access_key_id',
        ),
        migrations.RenameField(
            model_name='s3config',
            old_name='secretKey',
            new_name='secret_key',
        ),
        migrations.RenameField(
            model_name='sftpconfig',
            old_name='directory',
            new_name='remote_dir',
        ),
        migrations.RemoveField(
            model_name='fluxxconfig',
            name='instance',
        ),
        migrations.AddField(
            model_name='column',
            name='include_in_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='include_in_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fluxxconfig',
            name='base_url',
            field=models.CharField(default='https://fluxx.io', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s3config',
            name='region',
            field=models.CharField(default='us-east-1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sftpconfig',
            name='port',
            field=models.IntegerField(default=22),
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('export_location', models.CharField(max_length=255)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV')], max_length=10)),
                ('filter_string', models.CharField(blank=True, max_length=1000, null=True)),
                ('fluxx_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exporter.fluxxconfig')),
                ('s3_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exporter.s3config')),
                ('sftp_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exporter.sftpconfig')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='export_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exporter.exportjob'),
        ),
    ]
