# Generated by Django 5.1.3 on 2024-11-14 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0002_rename_clientid_fluxxconfig_client_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='s3Config',
            new_name='AmazonS3Config',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='export_job',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='related_entity',
        ),
        migrations.RenameField(
            model_name='exportjob',
            old_name='s3_config',
            new_name='amazon_s3_config',
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('include_in_export', models.BooleanField(default=False)),
                ('export_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exporter.exportjob')),
                ('related_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tables', to='exporter.table')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('include_in_export', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exporter.table')),
            ],
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
