# Generated by Django 5.1.3 on 2024-11-15 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0003_rename_s3config_amazons3config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='related_table',
        ),
        migrations.AddField(
            model_name='field',
            name='related_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tables', to='exporter.table'),
        ),
        migrations.AlterField(
            model_name='field',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='exporter.table'),
        ),
    ]
