# Generated by Django 5.1.3 on 2024-11-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0003_rename_s3config_amazons3config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='grant_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
