# Generated by Django 5.1.3 on 2024-11-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0004_exportjob_grant_ids'),
        ('exporter', '0004_remove_table_related_table_field_related_table_and_more'),
    ]

    operations = [
    ]
