# Generated by Django 5.2.4 on 2025-08-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0005_merge_20241118_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportjob',
            name='filter_string',
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('relator', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('export_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='exporter.exportjob')),
            ],
        ),
    ]
