# Generated by Django 5.2.3 on 2025-07-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0005_merge_20241118_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='export_location',
            field=models.FilePathField(allow_files=False, allow_folders=True, match='^[^\\.]', path='/', recursive=True),
        ),
    ]
