# Generated by Django 5.2.4 on 2025-09-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0006_remove_exportjob_filter_string_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='relator',
            field=models.CharField(choices=[('eq', 'Equals'), ('not-eq', 'Is Not Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('null', 'Is Null'), ('not-null', 'Is Not Null'), ('range', 'Between'), ('range-year-cal', 'Between Calendar Years'), ('yesterday', 'Yesterday'), ('today', 'Today'), ('tomorrow', 'Tomorrow'), ('last-n-days', 'Last N Days'), ('next-n-days', 'Next N Days'), ('days-n-ago', 'N Days Ago'), ('last-week', 'Last Week'), ('this-week', 'This Week'), ('next-week', 'Next Week'), ('last-n-weeks', 'Last N Weeks'), ('next-n-weeks', 'Next N Weeks'), ('weeks-n-ago', 'N Weeks Ago'), ('last-month', 'Last Month'), ('this-month', 'This Month'), ('next-month', 'Next Month'), ('last-n-months', 'Last N Months'), ('next-n-months', 'Next N Months'), ('months-n-ago', 'N Months Ago'), ('last-quarter', 'Last Quarter'), ('this-quarter', 'This Quarter'), ('next-quarter', 'Next Quarter'), ('last-n-quarters', 'Last N Quarters'), ('next-n-quarters', 'Next N Quarters'), ('quarters-n-ago', 'N Quarters Ago'), ('last-year', 'Last Year'), ('this-year', 'This Year'), ('next-year', 'Next Year'), ('last-n-years', 'Last N Years'), ('next-n-years', 'Next N Years'), ('years-n-ago', 'N Years Ago')], max_length=255),
        ),
    ]
