# Generated by Django 5.2.6 on 2025-09-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0007_alter_filter_relator'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='download_all_file_versions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amazons3config',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_id', models.IntegerField()),
                ('include_in_export', models.BooleanField(default=False)),
                ('export_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exporter.exportjob')),
                ('fluxx_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exporter.fluxxconfig')),
            ],
        ),
    ]
