# Generated by Django 5.2.4 on 2025-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0007_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazons3config',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
