# Generated by Django 5.2.6 on 2025-10-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0008_exportjob_download_all_file_versions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='export_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='exporter.exportjob'),
        ),
    ]
