# Generated by Django 5.2.6 on 2025-09-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0007_alter_filter_relator'),
        ('exporter', '0008_alter_amazons3config_name_alter_sftpconfig_name'),
    ]

    operations = [
    ]
