# Generated by Django 5.2.6 on 2025-10-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0009_alter_documenttype_export_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['name']},
        ),
    ]
