# Generated by Django 5.2.6 on 2025-09-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0009_merge_20250918_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='fluxx_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exporter.fluxxconfig'),
            preserve_default=False,
        ),
    ]
