# Generated by Django 5.2.14 on 2026-05-09 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0010_alter_documenttype_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxxconfig',
            old_name='client_id',
            new_name='old_client_id',
        ),
        migrations.RenameField(
            model_name='fluxxconfig',
            old_name='client_secret',
            new_name='old_client_secret',
        ),
    ]
