# Generated by Django 5.2.14 on 2026-05-09 01:48

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0011_rename_client_id_fluxxconfig_old_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxxconfig',
            name='client_id',
            field=django_cryptography.fields.encrypt(models.CharField(default=1, max_length=100)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluxxconfig',
            name='client_secret',
            field=django_cryptography.fields.encrypt(models.CharField(default=1, max_length=100)),
            preserve_default=False,
        ),
    ]
