# Generated by Django 5.2.14 on 2026-05-09 01:49

from django.db import migrations


def forwards_encrypted_char(apps, schema_editor):
    FluxxConfig = apps.get_model("exporter", "FluxxConfig")

    for obj in FluxxConfig.objects.all():
        obj.client_id = obj.old_client_id
        obj.client_secret = obj.old_client_secret
        obj.save()


def reverse_encrypted_char(apps, schema_editor):
    FluxxConfig = apps.get_model("exporter", "FluxxConfig")

    for obj in FluxxConfig.objects.all():
        obj.old_client_id = obj.client_id
        obj.old_client_secret = obj.client_secret
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0012_fluxxconfig_client_id_fluxxconfig_client_secret'),
    ]

    operations = [
        migrations.RunPython(forwards_encrypted_char, reverse_encrypted_char),
    ]
