# Generated by Django 5.2.14 on 2026-05-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0013_auto_20260509_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxxconfig',
            name='old_client_id',
        ),
        migrations.RemoveField(
            model_name='fluxxconfig',
            name='old_client_secret',
        ),
    ]
