name: build distributions
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    permissions:
      contents: write
    env:
      DIST_NAME: fluxx_exporter-${{ github.ref_name }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12'
          cache: pip

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build distribution
        run: pyinstaller fluxx_exporter.spec --distpath ${{ env.DIST_NAME }}

      - name: Sign Windows exe
        if: matrix.os == 'windows'
        uses: sslcom/esigner-codesign@v1.3.2
        with:
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          file_path: ${{ env.DIST_NAME }}/fluxx_exporter.exe
          output_path: ${{ env.DIST_NAME }}/${{ env.DIST_NAME}}.exe
          override: false
          malware_block: true
          clean_logs: true

      - name: Create zip file (windows)
        if: matrix.os == 'windows'
        run: |
          Compress-Archive -Path "${{ env.DIST_NAME }}" -DestinationPath "${{ env.DIST_NAME }}.zip"

      - name: Create zip file (linux)
        if: matrix.os != 'windows'
        run: |
            zip -r ${{ env.DIST_NAME }}.zip ${{ env.DIST_NAME }}

      - uses: softprops/action-gh-release@v2.5.0
        if: github.ref_type == 'tag'
        with:
          files: ${{ env.DIST_NAME }}.zip

      - uses: softprops/action-gh-release@v2.5.0
        if: github.ref_type == 'tag' && matrix.os == 'windows'
        with:
          files: ${{ env.DIST_NAME }}/${{ env.DIST_NAME }}.exe